title: Department of Statistics & Applied Probability Computing Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://UCSB-PSTAT.github.com/computing

aux_links:
  Template Repository: https://github.com/UCSB-PSTAT/computing