name: claat-build-pages

on:
  push:
    paths:
    - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: claat binary download
      run: | 
        wget https://github.com/googlecodelabs/tools/releases/download/v2.2.5/claat-linux-amd64 
        chmod u+x claat-linux-amd64
        
    - name: build codelabs pages
      run: |
        grep 'https://docs.google.com' README.md
        grep 'document' \
        cut -d'|' -f2 \
        cut -d'/' -f6 \
        sed 's/ *$//' \
        xargs -i ./claat-linux-amd64 export -o docs {}
